### ISSUE TITLE
Do you know how to style (or just hide) the magnifier icon?

### ISSUE THREAD

**Issue by Zeioth** [sachahjkl/wofi-arc-dark#1]
It looks tiny on HiDPI and it would be cool been able to resize it.

**Comment by sachahjkl** [comment]
Unfortunately, the magnifier icon is part of the native GTK element and can't be styled using wofi (or at all if I understand the doc correctly) : 

https://docs.gtk.org/gtk3/ctor.SearchEntry.new.html

![image](https://user-images.githubusercontent.com/32895534/207862019-8bcb7c59-0f4b-41e4-823f-ed340a02f762.png)

and here's the piece of code in wofi doing the element instantiation

![image](https://user-images.githubusercontent.com/32895534/207862150-370ba60c-939d-4ae9-a799-2eaa695debf6.png)

https://hg.sr.ht/~scoopta/wofi/browse/src/wofi.c?rev=tip#L1764

**Comment by sachahjkl** [comment]
> It looks tiny on HiDPI and it would be cool been able to resize it.

But maybe you can tweak your GTK settings to correctly setup HiDPI. Then the icon could be scaled properly
